### ISSUE TITLE
DBMON React seems faster. Any ideas why?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid-dbmon#1]
[React DBMON](http://mathieuancelin.github.io/js-repaint-perfs/react/)

Seems to get 100+ fps on my machine, while solid is getting 70-80.

I'm curious, what makes solid so much faster in Kraus, but slower in DBMON? Is that DBMON React sample equivalent to the Solid sample in terms of what they do?

**Comment by ryansolid** [comment]
Yeah I have a few ideas. That's interesting. I do most of my dev on a  weaker computer my React is about 60fps and Solid is about 70fps but it tends to dip after a few seconds. This is at 50%. At 5% Solid is way faster around 180fps to Reacts 120fps. But at 95% React slightly edges Solid out around 40fps. On my faster Computer Solid is faster too.

One thing I've noticed is that Solid gets slower over time. Let me know if you witness the same. It starts a lot faster than where it ends up. I have no idea why that happens yet. Perhaps there is a super small memory leak. I'm investigating, and suspect fixing it will stick Solid out ahead but probably not dominatingly so.

Other than that there are some reasons for the performance here. I'm actually in progress of writing an blog evaluating Solid's performance in different benchmarks. I don't know if you are aware of the history of this particular benchmark but it's the one that React used to make it's performance claims over the KVO frameworks of the time. This benchmark is about the worst case for libraries like Solid and Surplus (check out Knockout if you want to see a real naive implementation for the same sort of library). This bench just spams the UI with large blobs of always new data. There is no immutable referential ability to check changes. Now it's possible to write this in a way that only the deepest leaves are signals that update and I'm effectively doing that, but I purposely wrote this implementation to mimic the way you'd write it with React. 

This benchmark is also not a very typical use case. I know excuses, but atleast in the dev I've done I'm used to dealing with smaller data sets and partial updates. It's inefficient for every part of the chain to attack data this way. While I see potential for this DBMon type scenario real world updates wouldn't be likely at the 50% level but closer to the 5%.

JS Frameworks benchmark doesn't attack this way at all. It mimics more realistic flows for many applications where the big reconciliation is a one time hit and the rest are more targetted. Another thing you should be aware is that benchmark is using an older version of React (maybe 15), React 16 should be faster with it's incremental rendering. It basically skips rendering when data comes in too fast saving frames. Arguably "cheating" but you should be aware. I'm pretty sure some other libraries use similar techniques in this benchmark and others like it. JS Frameworks Benchmark can't be cheated that way.

Every benchmark has a billion caveats and tricks which is why I'm writing the Blog Article. I will also pass along an update when I figure out where the slowdown is coming from.

**Comment by ryansolid** [comment]
I changed the code to not leak and its definitely causing the slow down (I'm seeing around 100fps with solid at 50% on my slower computer). An issue with multi children with text nodes. I will clean it up and push a fix shortly.

**Comment by ryansolid** [comment]
Ok, fixed up and updated the demo page. Let me know if this makes things faster on your end. It is a tad unfortunate the DOM structure required here since having single child expressions is so much more optimized in general. Wrapping the elapsed number in a span like I tested earlier is a good 5-10% faster, but I have to go with the standard. End result is about 90fps on my slower computer.

**Comment by ryansolid** [comment]
I did hit a weird issue with browser plugins on my 3rd computer that only slowed down Solid and Surplus in benchmarks. But I changed the way I was text binding and seemed to go away. In any case I'm seeing very good results at this point so I'm considering this issue done.
